### ISSUE TITLE
[Suggestion]: Easier Management of Scribed Notes

### ISSUE THREAD

**Issue by lebrice** [mitliagkas/mitliagkas.github.io#1]
Hello Professor,

I have a suggestion:
It might be easier to manage scribed notes if you had the LaTeX source code (and accompanying PDFs) on your repository, and we would then make corrections and additions to the notes in the form of Pull Requests. 

I believe that this would make it easier on both us students and yourself, as we could propose alterations directly, rather than having to send zipped up source LaTeX, or PDFs, or OverLeaf links.

Let me know what you think,
-Fabrice

**Comment by mitliagkas** [comment]
That's a great suggestion, Fabrice, thanks for making it :)

Unfortunately, it didn't make it high enough on my priority list for me to act on it. Will try to collect them like that eventually.

**Comment by lebrice** [comment]
I would be happy to help in setting this up, if you want. I'd probably only need the zipped up notes for each lecture. 
Marking this as resolved, then! 👍
